imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    # The secret parameter is used to generate CSRF tokens
    secret:          058e7bdb3356d1e126041796db3b7371
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
#    session:
#        auto_start:     true

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/ezpublish_legacy

parameters:
